local F, G, V = unpack(select(2, ...))

local msButton = CreateFrame("Button", "button_gWorldmarkers", UIParent)
msButton:SetPoint("TOP", Minimap, "BOTTOM", -51, 1)
msButton:SetWidth(60)
msButton:SetHeight(25)
msButton:SetFrameStrata("BACKGROUND")
msButton:RegisterForClicks("LeftButtonDown")
msButton:SetScript("OnClick", function()
	gDMG_Toggle()
end)
F.addBackdrop(msButton)
F.createOverlay(msButton)


local clockButton = CreateFrame("Button", "button_gAutomatorConfig", UIParent)

clockButton:SetPoint("TOP", Minimap, "BOTTOM", 8, 1)
clockButton:SetWidth(60)
clockButton:SetHeight(25)
clockButton:SetFrameStrata("BACKGROUND")
clockButton:RegisterForClicks("LeftButtonDown")
clockButton:SetScript("OnClick", function()
	gAC_Toggle()
end)
F.addBackdrop(clockButton)
F.createOverlay(clockButton)


local fpsButton = CreateFrame("Button", "button_gWorldmarkers", UIParent)

fpsButton:SetPoint("TOP", Minimap, "BOTTOM", 67, 1)
fpsButton:SetWidth(60)
fpsButton:SetHeight(25)
fpsButton:SetFrameStrata("BACKGROUND")
fpsButton:RegisterForClicks("LeftButtonDown")
fpsButton:SetScript("OnClick", function()
	gWM_Toggle()
end)
F.addBackdrop(fpsButton)
F.createOverlay(fpsButton)
